### ISSUE TITLE
Wrong Name for Special Episodes

### ISSUE THREAD

**Issue by StancuFlorin** [ZeroQI/Absolute-Series-Scanner#56] opened 2016-09-05 14:48 UTC
Hello,

I have this files added on "Special" folder:

$ ls -l
total 226176
-r--r--r-- 1 StancuFlorin 197609 40264194 Sep  5 09:50 [Shinobi] One Piece S07 - Teatrul Pălăriilor de Paie - Chopperman [SD] [C9DF6C56].avi
-r--r--r-- 1 StancuFlorin 197609 47276404 Sep  5 09:50 [Shinobi] One Piece S08 - Teatrul Pălăriilor de Paie - Timpul Reportajului [SD] [1BECC418].avi
-r--r--r-- 1 StancuFlorin 197609 49249960 Sep  5 09:50 [Shinobi] One Piece S09 - Teatrul Pălăriilor de Paie - Obahan Time [SD] [01CB2798].avi
-r--r--r-- 1 StancuFlorin 197609 52283705 Sep  5 09:50 [Shinobi] One Piece S10 - Teatrul Pălăriilor de Paie - Fara Respect [HD] [00718C41].mp4
-r--r--r-- 1 StancuFlorin 197609 42354720 Sep  5 09:50 [Shinobi] One Piece S11 - Teatrul Pălăriilor de Paie - Timpul Monstrilor [SD] [E47AC6D6].avi

But the name and the picture of the episode on Plex is taken from episodes 7-11, not from special episodes 7-11.

Here are the logs:

[Plex Media Scanner.txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/455247/Plex.Media.Scanner.txt)

**Comment by ZeroQI** [comment] 2016-09-05 15:34
Name and episode picture are chosen by the AGENT, not the scanner, therefore not a scanner issue, so i will close this ticket

I could have checked if the special was associated to season 0 and not season 1 if you had included [...]/Plex Media Server/Logs/Plex Media Scanner (custom ASS).log (episodes info), but since it is in "Specials" folder it should be season 0.
- If using HAMA agent, attach HAMA log and scanner filelist to the HAMA issue you will create (if specials seen as s00e011 for S11 for example, if not the case, reply here with scanner custom log) so i reproduce your library.

**Closed by ZeroQI** 2016-09-05 15:34 UTC
