### ISSUE TITLE
Media Not Being Added

### ISSUE THREAD

**Issue by pairughdocks** [ZeroQI/Absolute-Series-Scanner#60] opened 2016-10-13 19:19 UTC
In my scanner log I can see that it's able to view the files, but I'm getting an ERROR: No Module in Absolute Series Scanner. Here is my log: https://ghostbin.com/paste/aw4sz

Any help would be appreciated.

**Comment by ZeroQI** [comment] 2016-10-13 20:15
Please check the readme for the fix and confirm if installing the runtime fixed it.
The forum has fix also by downgrading plex version

**Comment by pairughdocks** [comment] 2016-10-13 20:25
I don't see anything about a runtime in the README.md file. Am I missing something?

**Comment by ZeroQI** [comment] 2016-10-13 20:29
Known issues:

On windows install https://www.microsoft.com/en-us/download/details.aspx?id=48145 if you experience this error:


Jul 23, 2016 12:55:54.558 [5288] ERROR - Error scanning directory .
Jul 23, 2016 12:55:54.574 [5288] ERROR - No module in Absolute Series Scanner
Jul 23, 2016 12:55:54.574 [5288] ERROR - Error in Python: Looking up module:
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 8, in 
from lxml import etree # fromstring
ImportError: DLL load failed: The specified module could not be found.

**Comment by pairughdocks** [comment] 2016-10-13 20:29
I am not running Windows - sorry I forgot to mention that. I updated my last post.

**Comment by ZeroQI** [comment] 2016-10-13 20:31
On linux, permissions issues could prevent the scanner execution. Check hama readme for commands and posts the ones not documented if any.

**Comment by pairughdocks** [comment] 2016-10-13 20:38
I have full permission on my Plex folder, and followed all steps here: https://github.com/ZeroQI/Hama.bundle/blob/master/README.md

**Comment by ZeroQI** [comment] 2016-10-13 20:41
Please check the file doesn't contain html tags

**Comment by pairughdocks** [comment] 2016-10-13 20:45
Using mkvpropedit (from mkvtoolnix) there are no HTML tags

**Comment by ZeroQI** [comment] 2016-10-13 20:47
Attach the scanner file used but if it look right it will be a plex or linux execution issue

**Comment by pairughdocks** [comment] 2016-10-13 20:54
The scanner file is the one from GitHub - https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py I

**Comment by ZeroQI** [comment] 2016-10-13 21:03
So plex detect it. Not an error in the code otherwise error would be diferent. Rihjt ossue or plex isssue. Can't think of anything else

**Comment by pairughdocks** [comment] 2016-10-13 22:37
Rights, are assigned as per the installation guide. Plex is version 1.2.2 (latest PMS PlexPass release).

**Comment by Renari** [comment] 2016-10-24 13:29
I'm experiencing the same issue on debian, checking the permissions for /usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Scanners.bundle/Contents/Resources/Series the file is owned by root with 622 permissions (Plex Series Scanner is also here and has the same permissions). In my log I see the same error listed above but I also am not running Windows. I switched the library scanner back to Plex Series Scanner and it found the files that Absolute Series Scanner would not.

**Comment by ZeroQI** [comment] 2016-10-24 13:48
Error is that it is not loading a python library, not a code syntax issue... 
I am pretty sure that's not where the custom scanner go, as the customer scanner NEVER go in the same folder as Plex scanner...

Install guide stipulates to put here:".../Plex/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py" which wasn't followed.

Please follow https://forums.plex.tv/discussion/19396/how-to-install-a-custom-scanner
You will have to create both "Scanners" and "series folder"...

**Comment by Renari** [comment] 2016-10-24 14:48
I moved the files there, however it didn't seem to change anything.

```
Oct 24, 2016 10:46:55.437 [0x7fd6418c5800] ERROR - No module in VideoFiles
Oct 24, 2016 10:46:55.437 [0x7fd6418c5800] ERROR - Error scanning directory .
Oct 24, 2016 10:46:55.437 [0x7fd6418c5800] ERROR - No module in Absolute Series Scanner
Oct 24, 2016 10:46:55.437 [0x7fd6418c5800] ERROR - We got an error scanning in /home/renari/Videos
Oct 24, 2016 10:46:55.437 [0x7fd6418c5800] DEBUG -     * Scanning directory /home/renari/Videos/Bloodivores (parent: yes)
Oct 24, 2016 10:46:55.437 [0x7fd6418c5800] DEBUG - Adding file for scanner: /home/renari/Videos/Bloodivores/[HorribleSubs] Bloodivores - 03 [720p].mkv
Oct 24, 2016 10:46:55.437 [0x7fd6418c5800] DEBUG - Adding file for scanner: /home/renari/Videos/Bloodivores/[HorribleSubs] Bloodivores - 01 [720p].mkv
Oct 24, 2016 10:46:55.437 [0x7fd6418c5800] DEBUG - Adding file for scanner: /home/renari/Videos/Bloodivores/[HorribleSubs] Bloodivores - 04 [720p].mkv
Oct 24, 2016 10:46:55.437 [0x7fd6418c5800] DEBUG - Adding file for scanner: /home/renari/Videos/Bloodivores/[HorribleSubs] Bloodivores - 02 [720p].mkv
Oct 24, 2016 10:46:55.455 [0x7fd6418c5800] DEBUG - Directory had 4 files, database had 0 files, can't skip.
```
Here's an excerpt from the log.

**Comment by ZeroQI** [comment] 2016-10-24 15:27
"No module in VideoFiles"...  I am not loading VideoFiles from the original scanner in my scanner... Utils, Videos, Stack yes...
Did it ever worked or is that a new install?
check with a text editor if the first line is "# -*- coding: utf-8 -*-"

**Comment by Renari** [comment] 2016-10-24 16:04
It's a new install, I'll reinstall I guess and see if it makes a difference.

**Comment by Renari** [comment] 2016-10-25 00:02
OK, I'm back I've purged everything and started from scratch I can confirm that the above error was reproducible.

Here's an archive of all of the logs.
[PMSLogs_20161024-200117.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/549299/PMSLogs_20161024-200117.zip)

**Comment by ZeroQI** [comment] 2016-10-26 13:31
"I've fixed my issue, it appears the Absolute Series Scanner.py file I downloaded wasn't the raw version rather the webpage with the source code." 
Troubleshooting section list: 

If the scanner not listed in scanner list
Make sure you did create a "Series" library, as a "Movie" library will not show a "Series" scanner like ASS
Check file size and open the scanner file to check for corruption and that it does have html/xml tags. If it does, it was saved incorrectly and you should feel bad.

**Comment by ZeroQI** [comment] 2016-11-01 16:00
pairughdocks, any update ?

**Comment by ZeroQI** [comment] 2016-11-16 10:04
no update in 15 days, therefore no problems. closing

**Closed by ZeroQI** 2016-11-16 10:04 UTC

**Comment by ZeroQI** [comment] 2017-04-05 07:41
"ERROR - No module in VideoFiles" is present even when it works for me so plex cosmetic issue...

**Comment by wunc** [comment] 2017-10-06 01:04
@ZeroQI just a suggestion, but you might want to change the download link in your readme installation instructions to point to the raw file (https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/Scanners/Series/Absolute%20Series%20Scanner.py)

That would help avoid this issue with others. (like me!)
