### ISSUE TITLE
Kanji only filenames at root level result in empty show

### ISSUE THREAD

**Issue by TieSKey** [ZeroQI/Absolute-Series-Scanner#216] opened 2019-05-17 00:13 UTC
As the tittle (and the log) says, files with only kanji on the serie names seem to be failing. 
I'm not sure if the script does actually support this use case or I'm pushing it too much but reporting as requested by the log :P

```
=============================================================================================================================================================
Library: 'TV Shows', root: '/share/CACHEDEV2_DATA/World/Test', path: '', files: '3', dirs: '0'
Plex scan start: 2019-05-16 21:03:55,861294
plexignore_files: '[]', plexignore_dirs: '[]'
=============================================================================================================================================================
[file] 棋魂 - e01.mp4
[file] 棋魂 上巻.mp4
[file] 棋魂 下巻.mp4
=============================================================================================================================================================
Plex scan end: 2019-05-16 21:03:55,864558
```

```
=============================================================================================================================================================
Library: 'TV Shows', root: '/share/CACHEDEV2_DATA/World/Test', path: '', files: '3', dirs: '0'
Plex scan start: 2019-05-16 21:03:55,866391
=============================================================================================================================================================
show: '', s01e001-001, file: '/share/CACHEDEV2_DATA/World/Test/棋魂 - e01.mp4' has show empty, report logs to dev ASAP
"" s01e001                         "ANIDB_RX-5" "Episode 01" "棋魂 - e01.mp4"
show: '', s00e501-501, file: '/share/CACHEDEV2_DATA/World/Test/棋魂 上巻.mp4' has show empty, report logs to dev ASAP
"" s00e501                         "__" "" "棋魂 上巻.mp4"
show: '', s00e502-502, file: '/share/CACHEDEV2_DATA/World/Test/棋魂 下巻.mp4' has show empty, report logs to dev ASAP
"" s00e502                         "__" "" "棋魂 下巻.mp4"
root level manual call to Grouping folders
=============================================================================================================================================================
Plex scan end: 2019-05-16 21:03:55,873563
```

**Comment by ZeroQI** [comment] 2019-05-17 05:49
It used to work, will reproduce and fix.

**Comment by TieSKey** [comment] 2019-06-17 04:18
Hey, never saw your edit. I'm new to plex and your agent, this is the first version I tried so I can't help you with that :S

**Comment by ZeroQI** [comment] 2019-06-26 06:52
```
=============================================================================================================================================================
Library: 'no valid X-Plex-Token.id', root: 'C:\Users\benja\Videos\_temp 4', path: 'Test', files: '3', dirs: '0'
Plex scan start: 2019-06-26 07:50:35,144000
=============================================================================================================================================================
No forced id found in series folder name nor id file
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc_count: {'\xe4\xb8\x8b\xe5\xb7\xbb': 1, 'mp4': 3, '\xe4\xb8\x8a\xe5\xb7\xbb': 1, '\xe6\xa3\x8b\xe9\xad\x82': 3, 'e01': 1}
misc_words: []
-------------------------------------------------------------------------------------------------------------------------------------------------------------
"Test" s01e001                         "Word Search" "" "棋魂 - e01.mp4"
"Test" s00e501                         "__" "" "棋魂 上巻.mp4"
"Test" s00e502                         "__" "" "棋魂 下巻.mp4"
=============================================================================================================================================================
Plex scan end: 2019-06-26 07:50:35,149000
```
Used your filenames, works for me.
Issue is Plex/OS/Machine specific seemingly

**Comment by ZeroQI** [comment] 2019-08-31 14:32
could you comment line 924 anr report if it fixes ""棋魂 - e01.mp4"" :
if not path  and not " - Complete Movie" in file:  show = clean_string( " `".join(words[:words.index(word)]) if words.index(word)>0 else "No title", False)    # root folder and 
        `

**Comment by TieSKey** [comment] 2019-08-31 15:01
```
=============================================================================================================================================================
Library: 'TV Shows', root: 'D:\Test', path: '', files: '2', dirs: '0'
Plex scan start: 2019-08-31 11:56:19,067000
=============================================================================================================================================================
show: '', s01e001-001, file: 'D:\Test\棋魂 - e01.mp4' has show empty, report logs to dev ASAP
"" s01e001                         "ANIDB_RX-5" "Episode 01" "棋魂 - e01.mp4"
show: '', s01e002-002, file: 'D:\Test\棋魂 - e02.mp4' has show empty, report logs to dev ASAP
"" s01e002                         "ANIDB_RX-5" "Episode 02" "棋魂 - e02.mp4"
root level manual call to Grouping folders
=============================================================================================================================================================
Plex scan end: 2019-08-31 11:56:19,069000

```

```
=============================================================================================================================================================
Library: 'TV Shows', root: 'D:\Test', path: '', files: '2', dirs: '0'
Plex scan start: 2019-08-31 11:56:19,066000
plexignore_files: '[]', plexignore_dirs: '[]'
=============================================================================================================================================================
[file] 棋魁E- e01.mp4
[file] 棋魁E- e02.mp4
=============================================================================================================================================================
Plex scan end: 2019-08-31 11:56:19,067000

```

Not sure what is that E added to the filename in this log.

**Comment by ZeroQI** [comment] 2019-08-31 16:49
title corrupted by:         `filename = encodeASCII(filename)`
Please test and report, should be fixed and movies at root be s01e01 while i was at it

**Closed** 2019-08-31 16:49 UTC
Labels: bug

**Comment by TieSKey** [comment] 2019-09-01 13:28
Seems to be working. Good job ;)
