### ISSUE TITLE
Issue w/titles & episode mapping

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#48] opened 2016-07-08 21:05 UTC
As you can see, once it hits the 2 in 2016, it's making the rest the title.
```

2016-07-08 17:02:14 =============================================================================================================================================================
2016-07-08 17:02:14 Scanner call - root: 'Z:\Anime Series', path: 'Berserk (2016)', dirs: '0', files: '6'
2016-07-08 17:02:14 =============================================================================================================================================================
2016-07-08 17:02:14 file: 'Z:\Anime Series\Berserk (2016)\tvdb2.id', ext: 'id' not in video_ext
2016-07-08 17:02:14 folder_show: 'Berserk (2016) [tvdb2-307111]', folder_season: 'None', tvdb mode: '2', tvdb id: '307111'
2016-07-08 17:02:14 TVDB season mode (2) enabled, serie url: 'https://thetvdb.com/api/A27AD9BE0DA63333/series/307111/all/en.xml'
2016-07-08 17:02:57 abs_manual_placement_worked: 'True', abs_manual_placement_info: '[]'
2016-07-08 17:02:57 unknown_series_length: False, tvdb_mapping: {1: (1, 1), 2: (1, 2), 3: (1, 3), 4: (1, 4), 5: (1, 5), 6: (1, 6), 7: (1, 7), 8: (1, 8), 9: (1, 9)}
2016-07-08 17:02:57 "Berserk (2016) [tvdb2-307111]" s0000e001 "Berserk (2016) - 0x01 - Golden Age Arc I Egg of the King.mkv" "0" "Golden Age Arc I Egg of the King" 
2016-07-08 17:02:57 "Berserk (2016) [tvdb2-307111]" s0000e002 "Berserk (2016) - 0x02 - Golden Age Arc II The Battle for Doldrey.mkv" "0" "Golden Age Arc II The Battle for Doldrey" 
2016-07-08 17:02:57 "Berserk (2016) [tvdb2-307111]" s0000e003 "Berserk (2016) - 0x03 - Golden Age Arc III The Advent.mkv" "0" "Golden Age Arc III The Advent" 
2016-07-08 17:02:57 "Berserk (2016) [tvdb2-307111]" s0001e001 "Berserk (2016) - 1 - The Branded Swordsman.mkv" "6 ) - 1 - The Branded Swordsman" 
2016-07-08 17:02:58 "Berserk (2016) [tvdb2-307111]" s0001e002 "Berserk (2016) - 2 - The Holy Iron Chain Knights.mkv" "016 ) - 2 - The Holy Iron Chain Knights" 
2016-07-08 17:02:58 -------------------------------------------------------------------------------------------------------------------------------------------------------------


```

<img width="172" alt="screen shot 2016-07-08 at 5 02 10 pm" src="https://cloud.githubusercontent.com/assets/18091557/16701466/f98d001e-452d-11e6-8a93-248978035fd9.png">

**Comment by sven-7** [comment] 2016-07-08 21:11
I've had this happen with multiple shows, that I've just renamed...but here are some examples:

- Dragon Ball Super - 1 - The Peace Prize. Who'll Get the 100 Million Zeny!
- Sailor Moon Crystal Season 3 ([As you can see](http://thetvdb.com/?tab=season&seriesid=275039&seasonid=662722&lid=7), there are two (correctly) labeled episodes with Act 27.  Until that point, the episode act and absolute number lined up.  The scanner sometimes does not like seeing the two different ones. 
- Monster ([Episodes 11, 41, and 55](http://thetvdb.com/?tab=season&seriesid=74599&seasonid=7712&lid=7))

**Comment by EndOfLine369** [comment] 2016-07-09 00:00
Its this line. I'll have to see how to make it better.
`title = clean_string( " ".join(words)[" ".join(words).lower().index(ep)+len(ep):] )`
Its seeing the '1' & '2' in '2016' as where we matched the episode number and taking everything to the right of it as the title.

**Comment by EndOfLine369** [comment] 2016-07-09 05:00
I believe this should fix it. Are there any other file names you want me to test?

```python
FROM:
title = clean_string( " ".join(words)[" ".join(words).lower().index(ep)+len(ep):] )
TO:
title = clean_string( " ".join(words[words.index(word):])[" ".join(words[words.index(word):]).lower().index(ep)+len(ep):] )
```
Testing:
```python
>>> words = "Berserk (2016) - 1 - The Branded Swordsman".split()
>>> words
['Berserk', '(2016)', '-', '1', '-', 'The', 'Branded', 'Swordsman']
>>> word = "1"; ep = "1"
>>> " ".join(words)[" ".join(words).lower().index(ep)+len(ep):]
'6) - 1 - The Branded Swordsman'
>>> " ".join(words[words.index(word):])[" ".join(words[words.index(word):]).lower().index(ep)+len(ep):]
' - The Branded Swordsman'
>>>
>>> words = "Berserk (2016) - 2 - The Holy Iron Chain Knights.mkv".split()
>>> words
['Berserk', '(2016)', '-', '2', '-', 'The', 'Holy', 'Iron', 'Chain', 'Knights.mkv']
>>> word = "2"; ep = "2"
>>> " ".join(words)[" ".join(words).lower().index(ep)+len(ep):]
'016) - 2 - The Holy Iron Chain Knights.mkv'
>>> " ".join(words[words.index(word):])[" ".join(words[words.index(word):]).lower().index(ep)+len(ep):]
' - The Holy Iron Chain Knights.mkv'
>>>
>>> words = "Dragon Ball Z-219-Energy Drain".split()
>>> words
['Dragon', 'Ball', 'Z-219-Energy', 'Drain']
>>> word = 'Z-219-Energy'; ep = "219"
>>> " ".join(words)[" ".join(words).lower().index(ep)+len(ep):]
'-Energy Drain'
>>> " ".join(words[words.index(word):])[" ".join(words[words.index(word):]).lower().index(ep)+len(ep):]
'-Energy Drain'
```
FYI, ticket from where it was orig changed was https://github.com/ZeroQI/Absolute-Series-Scanner/issues/43.

**Comment by sven-7** [comment] 2016-07-09 05:39
Please check:

-  Sailor Moon Crystal - 35 - Act 34. Infinity 8 - Infinite Labyrinth 1  (I had this register as ep 34 and Plex saw it as a duplicate)
- Dragon Ball Super - 1 - The Peace Prize. Who'll Get the 100 Million Zeny!
- The Monster episodes  (11, 41, and 55), if you can.  Two have 511 in the title, which made them into Ep 511.

The other shows I have years in -- Hunter X Hunter (2011), JoJo's Bizzarre Adventure (2012), etc... -- don't seem to have been affected by this.

**Comment by EndOfLine369** [comment] 2016-07-09 05:41
I need your filenames please.

**Comment by sven-7** [comment] 2016-07-09 05:50
Monster (11, 41, 55):

```
A:\Anime Series\Monster\Monster - 1 - Herr Doctor Tenma.avi
A:\Anime Series\Monster\Monster - 10 - A Past Erased.avi
A:\Anime Series\Monster\Monster - 11 - Kinderheim 511.avi
A:\Anime Series\Monster\Monster - 12 - A Meager Little Experiment.avi
A:\Anime Series\Monster\Monster - 13 - Petra and Schumann.avi
A:\Anime Series\Monster\Monster - 14 - The Only Man Left, The Only Woman Left.avi
A:\Anime Series\Monster\Monster - 15 - Be My Baby.avi
A:\Anime Series\Monster\Monster - 16 - Wolf's Confession.avi
A:\Anime Series\Monster\Monster - 17 - Reunion.avi
A:\Anime Series\Monster\Monster - 18 - The Fifth Spoonful of Sugar.avi
A:\Anime Series\Monster\Monster - 19 - Abyss of the Monster.avi
A:\Anime Series\Monster\Monster - 2 - Downfall.avi
A:\Anime Series\Monster\Monster - 20 - Journey to Freiham.avi
A:\Anime Series\Monster\Monster - 21 - A Wonderful Holiday.avi
A:\Anime Series\Monster\Monster - 22 - Lunge's Trap.avi
A:\Anime Series\Monster\Monster - 23 - Eva's Confession.avi
A:\Anime Series\Monster\Monster - 24 - Men's Table.avi
A:\Anime Series\Monster\Monster - 25 - The Thursday Boy.avi
A:\Anime Series\Monster\Monster - 26 - Secret Forest.avi
A:\Anime Series\Monster\Monster - 27 - Evidence.avi
A:\Anime Series\Monster\Monster - 28 - Just One Case.avi
A:\Anime Series\Monster\Monster - 29 - Execution.avi
A:\Anime Series\Monster\Monster - 3 - A Murder.avi
A:\Anime Series\Monster\Monster - 30 - A Certain Decision.avi
A:\Anime Series\Monster\Monster - 31 - Into the Light of Day.avi
A:\Anime Series\Monster\Monster - 32 - Sanctuary.avi
A:\Anime Series\Monster\Monster - 33 - Scenes from Childhood.avi
A:\Anime Series\Monster\Monster - 34 - At the End of the Darkness.avi
A:\Anime Series\Monster\Monster - 35 - Nameless Hero.avi
A:\Anime Series\Monster\Monster - 36 - The Monster of Chaos.avi
A:\Anime Series\Monster\Monster - 37 - A Monster Without a Name.avi
A:\Anime Series\Monster\Monster - 38 - The Demon In My Sight.avi
A:\Anime Series\Monster\Monster - 39 - The Hell In His Sight.avi
A:\Anime Series\Monster\Monster - 4 - Night of the Execution.avi
A:\Anime Series\Monster\Monster - 40 - Grimmer.avi
A:\Anime Series\Monster\Monster - 41 - Ghosts of 511.avi
A:\Anime Series\Monster\Monster - 42 - The Adventures of the Magnificent Steiner.avi
A:\Anime Series\Monster\Monster - 43 - Detective Suk.avi
A:\Anime Series\Monster\Monster - 44 - Two Darknesses.avi
A:\Anime Series\Monster\Monster - 45 - The Monster's Afterimage.avi
A:\Anime Series\Monster\Monster - 46 - Point of Contact.avi
A:\Anime Series\Monster\Monster - 47 - Nightmare's Door.avi
A:\Anime Series\Monster\Monster - 48 - The Scariest Thing.avi
A:\Anime Series\Monster\Monster - 49 - The Cruelest Thing.avi
A:\Anime Series\Monster\Monster - 5 - The Girl of Heidelberg.avi
A:\Anime Series\Monster\Monster - 50 - Mansion of Roses.avi
A:\Anime Series\Monster\Monster - 51 - The Monster's Love Letter.avi
A:\Anime Series\Monster\Monster - 52 - Lawyer.avi
A:\Anime Series\Monster\Monster - 53 - Decision.avi
A:\Anime Series\Monster\Monster - 54 - Escape.avi
A:\Anime Series\Monster\Monster - 55 - Room 402.avi
A:\Anime Series\Monster\Monster - 56 - The Unending Journey.avi
A:\Anime Series\Monster\Monster - 57 - That Night.avi
A:\Anime Series\Monster\Monster - 58 - An Unpleasant Job.avi
A:\Anime Series\Monster\Monster - 59 - The Man Who Saw the Devil.avi
A:\Anime Series\Monster\Monster - 6 - The Missing.avi
A:\Anime Series\Monster\Monster - 60 - The Man Who Knew Too Much.avi
A:\Anime Series\Monster\Monster - 61 - The Door of Memory.avi
A:\Anime Series\Monster\Monster - 62 - A Fun Dining Table.avi
A:\Anime Series\Monster\Monster - 63 - Unrelated Murders.avi
A:\Anime Series\Monster\Monster - 64 - The Baby's Depression.avi
A:\Anime Series\Monster\Monster - 65 - Johan's Footprints.avi
A:\Anime Series\Monster\Monster - 66 - Welcome Back.avi
A:\Anime Series\Monster\Monster - 67 - I'm Home.avi
A:\Anime Series\Monster\Monster - 68 - Ruhenheim.avi
A:\Anime Series\Monster\Monster - 69 - A Peaceful Home.avi
A:\Anime Series\Monster\Monster - 7 - House of Tragedy.avi
A:\Anime Series\Monster\Monster - 70 - Town Bloodbath.avi
A:\Anime Series\Monster\Monster - 71 - The Magnificent Steiner's Rage.avi
A:\Anime Series\Monster\Monster - 72 - Man Without a Name.avi
A:\Anime Series\Monster\Monster - 73 - The Landscape of the End.avi
A:\Anime Series\Monster\Monster - 74 - The Real Monster.avi
A:\Anime Series\Monster\Monster - 8 - Pursued.avi
A:\Anime Series\Monster\Monster - 9 - The Girl and the Seasoned Soldier.avi
```

Dragon Ball Super (Ep 1):
```
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 1 - The Peace Prize. Who'll Get the 100 Million Zeny!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 10 - Show me Goku! The Power of Super Saiyan God!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 11 - Let's Keep Going Beerus-Sama! The Battle Of Gods Continues!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 12 - The Universe Crumbles! Clash! The God of Destruction vs Super Saiyan God!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 13 - Goku, Go Surpass Super Saiyan God!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 14 - This is Every Last Bit of My Power! The Battle of Gods Concludes!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 15 - Heroic Satan, Cause a Miracle! A Challenge From Outer Space!!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 16 - Vegeta Becomes a Pupil! Take Down Whis!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 17 - Keep This a Secret From Chi-Chi! I Wanna Go Train Too!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 18 - I've Come Too! Training Begins on Beerus' Planet!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 19 - Despair Once More! Revival of the Evil Emperor, Freeza!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 2 - To the Promised Resort! Vegeta's Family Vacation!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 20 - Warning from Jaco! Freeza and 1,000 Soldiers are Fast Approaching!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 21 - The Revenge Begins! The Freeza Army's Malice Strikes Gohan!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 22 - Change! An Impossible Revival! The Name's Ginyu!!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 23 - The Earth and Gohan in Dire Peril! Come Quick, Son Goku!!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 24 - Clash Freeza vs Son Goku! This is the Fruit of My Training!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 25 - An All-Out Battle! The Vengeful Golden Freeza.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 26 - A Chance of Victory in a Pinch! It is Time for a Counterattack, Son Goku!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 27 - The Earth Explodes! The Final, Conclusive Kamehame-ha!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 28 - The 6th Universe's God of Destruction - His Name's Champa.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 29 - There's Going to Be a Martial Arts Competition! The Team Captain is a Guy Stronger Than Even Goku.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 3 - Where's the Rest of My Dream! Find the Super Saiyan God!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 30 - Preparing for the Martial Arts Matches - Who Will the Last Two on the Team Be!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 31 - To Zuno-sama! Ask the Whereabouts of the Super Dragon Balls!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 32 - The Matches Begin! Everybody Heads to the Nameless Planet!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 33 - Be Amazed, Universe 6! This is Super Saiyan Son Goku!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 34 - Piccolo VS Frost - Bet Everything on the Makankosappo!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 35 - Change Your Fury Into Power! Vegeta's All-Out Battle.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 36 - An Unexpected Struggle! Vegeta's Explosion of Anger!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 37 - Don't Forget Your Saiyan Pride! Vegeta VS the Saiyan from Universe 6.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 38 - Universe 6's Strongest Warrior! Enter Hit, the Assassin!!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 39 - A Counter-Attack With an Improved Time-Skip! Will Goku's New Move be Unleashed!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 4 - Aim for the Dragon Balls! The Pilaf Gang's Master Plan!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 40 - The Long Awaited Conclusion! Was it Beerus or Champa Who Won.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 41 - Appear, Divine Dragon - And Grant my Wish, Pretty Please!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 42 - A Turbulent Victory Celebration! Facing Off at Last! Monaka VS Son Goku.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 43 - Goku Can't Control His Ki! A Struggle to Look After Pan.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 44 - The Seal on Planet Pot-au-feu - The Secret of the Unleashed.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 45 - Vegeta is Disappearing! The Terror of the Vegeta Clone!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 46 - Goku VS the Vegeta Clone! Who Will Win!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 47 - SOS from the Future! A New Black Enemy Appears!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 48 - HOPE!! Again - Trunks Wakes Up in the Present!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 49 - A Message From the Future - Goku Black Invades!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 5 - A Battle on Kaio's Planet! Goku vs God of Destruction Beerus.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 50 - Goku vs. Black! The Road Towards the Sealed Future.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 6 - Don't Anger the God of Destruction! A Tense Birthday Party.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 7 - How Dare You Hurt My Bulma! Vegeta's Total, Furious Change!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 8 - Goku Arrives! A Last Chance From Beerus-sama!.mkv
A:\Anime Series\Dragon Ball Super\Dragon Ball Super - 9 - Sorry for the Wait, Beerus-sama. The Super Saiyan God Is Finally Born!.mkv
```

Sailor Moon Crystal (a lot of them broke 27+):
```
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 1 - Act 1. Usagi ~Sailor Moon~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 10 - Act 10. Moon.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 11 - Act 11. Reunion ~Endymion~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 12 - Act 12. Enemy ~Queen Metalia~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 13 - Act 13. Final Battle ~Reincarnation~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 14 - Act 14. Conclusion and Commencement ~Petite Étrangère~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 15 - Act 15. Infiltration ~Sailor Mars~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 16 - Act 16. Abduction ~Sailor Mercury~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 17 - Act 17. Secrecy ~Sailor Jupiter~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 18 - Act 18. Invasion ~Sailor Venus~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 19 - Act 19. Time Warp ~Sailor Pluto~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 2 - Act 2. Ami ~Sailor Mercury~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 20 - Act 20. Crystal Tokyo ~King Endymion~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 21 - Act 21. Complication ~Nemesis~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 22 - Act 22. Hidden Agenda ~Nemesis~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 23 - Act 23. Covert Maneuvers ~Wiseman~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 24 - Act 24. Attack ~Black Lady~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 25 - Act 25. Showdown ~Death Phantom~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 26 - Act 26. Replay ~Never Ending~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 27 - Act 27. Infinity 1 - Premonition (Part 1).mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 28 - Act 27. Infinity 1 - Premonition (Part 2).mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 29 - Act 28. Infinity 2 - Ripples.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 3 - Act 3. Rei ~Sailor Mars~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 30 - Act 29. Infinity 3 - Two New Soldiers.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 31 - Act 30. Infinity 4 - Haruka Tenoh, Michiru Kaioh ~Sailor Uranus, Sailor Neptune~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 32 - Act 31. Infinity 5 - Setsuna Meiou ~Sailor Pluto~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 33 - Act 32. Infinity 6 - Three Guardians.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 34 - Act 33. Infinity 7 - Transformation ~Super Sailor Moon~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 35 - Act 34. Infinity 8 - Infinite Labyrinth 1.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 36 - Act 35. Infinity 9 - Infinite Labyrinth 2.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 37 - Act 36. Infinity 10 - Infinite ~Upper Atmosphere~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 38 - Act 37. Infinity 11 - Infinite ~Judge~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 39 - Act 38. Infinity 12 - Infinite ~Journey~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 4 - Act 4. Masquerade ~Dance Party~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 5 - Act 5. Makoto ~Sailor Jupiter~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 6 - Act 6. Tuxedo Mask.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 7 - Act 7. Mamoru Chiba ~Tuxedo Mask~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 8 - Act 8. Minako ~Sailor V~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 9 - Act 9. Serenity ~Princess~.mkv
```

**Comment by EndOfLine369** [comment] 2016-07-09 05:53
Wait, just reread your post. your no longer talking about what this ticket is about when it comes to title name in Plex from ASS before metadata overite.

**Comment by EndOfLine369** [comment] 2016-07-09 05:54
What is your issue your raising now? Incorrect season/episode assignment for some of your files? I'll need your ASS log for that.

**Comment by EndOfLine369** [comment] 2016-07-09 05:55
Scanner log and filelist files please.

**Comment by sven-7** [comment] 2016-07-09 06:01
I think it's related.

Looking through these logs I previously renamed the files I was having problems with to (Series - Abs#) from (Series - Abs# - Title).  I've now renamed them to the latter, re-scanned, and here are the logs.  Monster and Dragon Ball Super seem to be doing okay.  Sailor Moon Crystal seems to have two issues.  

I can do a full refresh to see if that pops up anything as the scanner skipped over a bunch of things because there were no changes. 

[ASS Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/355418/ASS.Logs.zip)

**Comment by EndOfLine369** [comment] 2016-07-09 06:09
No issues seen with these:
```
2016-07-09 01:56:26 "Dragon Ball Super [tvdb3-295068]" s0001e001 "Dragon Ball Super - 1 - The Peace Prize. Who'll Get the 100 Million Zeny!.mkv" "The Peace Prize Who'll Get the 100 Million Zeny!" 

2016-07-09 01:56:24 "Monster [tvdb-74599]" s0001e011 "Monster - 11 - Kinderheim 511.avi" "Kinderheim 511" 
2016-07-09 01:56:24 "Monster [tvdb-74599]" s0001e041 "Monster - 41 - Ghosts of 511.avi" "Ghosts of 511" 
2016-07-09 01:56:24 "Monster [tvdb-74599]" s0001e051 "Monster - 51 - The Monster's Love Letter.avi" "The Monster's Love Letter" 
```
These are suspect:
```
2016-07-09 01:56:42 "Sailor Moon Crystal [tvdb3-275039]" s0001e001 "Sailor Moon Crystal - 35 - Act 34. Infinity 8 - Infinite Labyrinth 1.mkv"
2016-07-09 01:56:42 "Sailor Moon Crystal [tvdb3-275039]" s0001e002 "Sailor Moon Crystal - 36 - Act 35. Infinity 9 - Infinite Labyrinth 2.mkv"
```

**Comment by EndOfLine369** [comment] 2016-07-09 06:11
And note this is not the same issue so will have to review other pieces of the code. So the above fix has nothing to do with this bug.

**Comment by sven-7** [comment] 2016-07-10 14:29
Okay -- do you want me to open a second ticket?

**Comment by EndOfLine369** [comment] 2016-07-10 21:05
Naw. Working on both in this ticket is fine. 
And I believe I know what the issue is for Sailor Moon Crystal.

**Comment by EndOfLine369** [comment] 2016-07-10 22:33
Ok, think I got what is needed.
```
BEFORE:
2016-07-10 17:20:31 "Sailor Moon Crystal" s0001e001 "Sailor Moon Crystal - 35 - Act 34. Infinity 8 - Infinite Labyrinth 1.mkv"
2016-07-10 17:20:31 "Sailor Moon Crystal" s0001e002 "Sailor Moon Crystal - 36 - Act 35. Infinity 9 - Infinite Labyrinth 2.mkv"

AFTER:
2016-07-10 17:26:25 "Sailor Moon Crystal" s0001e035 "Sailor Moon Crystal - 35 - Act 34. Infinity 8 - Infinite Labyrinth 1.mkv" "3" "Act 34 Infinity 8 - Infinite Labyrinth 1" 
2016-07-10 17:26:25 "Sailor Moon Crystal" s0001e036 "Sailor Moon Crystal - 36 - Act 35. Infinity 9 - Infinite Labyrinth 2.mkv" "3" "Act 35 Infinity 9 - Infinite Labyrinth 2" 
```
Issue was that a number was the last word we processed in the first loop try before trying regex matching.

**Comment by EndOfLine369** [comment] 2016-07-10 22:37
Please test https://gist.github.com/EndOfLine369/4ff707c70fd64f06b708410e957b2e86 and get back if you see any more issues.

**Comment by EndOfLine369** [comment] 2016-07-10 22:38
Related to these two issues :wink:

**Comment by sven-7** [comment] 2016-07-11 02:45
Okay, thanks.  Will test within the next day.  Thanks! :thumbsup:

Just noticed this, and perhaps it's always been this way, but in your 'after' example, it has the sailor moon episodes as s0001e035/36.  Shouldn't that be s0003?

**Comment by sven-7** [comment] 2016-07-11 02:51
Tested -- good to go for both issues!  Thanks again!

**Comment by EndOfLine369** [comment] 2016-07-11 05:20
Fix committed to the master.

**Closed by EndOfLine369** 2016-07-11 05:20 UTC
Labels: bug

**Comment by ZeroQI** [comment] 2016-07-11 16:43
Well done, this would have randomly impacted other things
