### ISSUE TITLE
Recognizing Movies named with episode title

### ISSUE THREAD

**Issue by pathsny** [ZeroQI/Absolute-Series-Scanner#316] opened 2020-11-25 22:50 UTC
## Platform
Operating system and version: Truenas-12.0-Stable (Freebsd 11.2-RELEASE-p9)
Plex version:  1.19.5.3112 

## Expected Behavior
Correctly recognise movie files

## Current Behavior
Movie parts are recognised incorrectly

## Steps to Reproduce
1. Here is my current directory structure for movies
    - Tenkuu no Shiro Laputa
       - anidb.id (contains 331)
       - Tenkuu no Shiro Laputa - Part 1 of 2 [a4e] [(X-2)].mkv
       - Tenkuu no Shiro Laputa - Part 2 of 2 [a4e] [(X-3)].mkv
2. My movie files are typically named as Movie Name - Part name [groupname][metadata I had added at one point to help me when I used to use Kodi]
   The issue here is that it believes these are episodes 1 and 2 which is "the complete movie" and "part 1 of 2".

Scanner Log Contents
```
=============================================================================================================================================================
Library: 'Anime', root: '/media/Anime/Movies', path: 'Tenkuu no Shiro Laputa', files: '2', dirs: '0'
Plex scan start: 2020-11-24 12:54:44,707472
=============================================================================================================================================================
Forced ID (source file) - source: "anidb", id: "331"
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc_count: {'Laputa': 2, 'no': 2, 'of': 2, '1': 1, 'Part': 2, 'Tenkuu': 2, '2': 3, 'Shiro': 2}
misc_words: []
-------------------------------------------------------------------------------------------------------------------------------------------------------------
"Tenkuu no Shiro Laputa [anidb-331]" s01e001                         "Word Search" "Of 2" "Tenkuu no Shiro Laputa - Part 1 of 2 [a4e] [(X-2)].mkv"
"Tenkuu no Shiro Laputa [anidb-331]" s01e002                         "ANIDB_RX-5" "Of 2" "Tenkuu no Shiro Laputa - Part 2 of 2 [a4e] [(X-3)].mkv"
=============================================================================================================================================================
Plex scan end: 2020-11-24 12:54:44,722230
```

## Resolution
How best can I get my movie files recognized correctly?

**Comment by ZeroQI** [comment] 2020-11-25 23:13
Working as designed since you use a series library. Try the numbering
conventions there...

https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/

**Comment by pathsny** [comment] 2020-11-25 23:38
Perhaps I'm missing something but my understanding is if I want to import anime and make use of anidb data, then with Hama the recommendation is to use a Series Library and not a separate movie library? Is there a different way to use Hama as a movie library that I am perhaps missing?

I tried renaming my files using the approach on that link and they got recognised as episodes 501 and 502 instead :X. Is there a way to name the files so that they get recognised as multiple files of a single movie that plays all at once?

**Comment by ZeroQI** [comment] 2020-11-26 07:32
I don't think the series scanner is equipped to have multiple part of the same movies within the same ep number. You would have to make the numbering in square brackets so the scanner sees it as the same ep number

Also you could use ep 2 and 3 numbering since and use it for 2 pats movies

https://anidb.net/anime/331

**Comment by pathsny** [comment] 2020-11-26 18:38
Interestingly I just performed a test with a tv show and created a "fake" two part episode. 
  - 009-1 - episode 01 [E-D] - part1.mkv
  - 009-1 - episode 01 [E-D] - part2.mkv

This is actually recognized as a single episode and plays as a single file. That behavior is why I'm trying to get them to stack together. I guess having it show up as a stack will require returning the same episode number.

**Comment by ZeroQI** [comment] 2020-11-26 22:21
Indeed if returning the same ep number the code just stacks every thing with the same ep number...

**Comment by pathsny** [comment] 2020-11-27 06:17
So I took another stab at it. I first tried naming it this way

- Tenkuu no Shiro Laputa - [a4e] - part1.mkv
- Tenkuu no Shiro Laputa - [a4e] - part2.mkv

It did show up  as a single video, but as a single special numbered 501 and named `part1`.

So I then tried another approach.

- Tenkuu no Shiro Laputa - Complete Movie - part1 [a4e].mkv
- Tenkuu no Shiro Laputa - Complete Movie - part2 [a4e].mkv

This gets rendered as a single video named `Tenkuu no Shiro Laputa Complete Movie`

Given how well you know the naming scheme, is there another naming you'd recommend?

**Comment by ZeroQI** [comment] 2021-01-04 10:43
Readme notes for films in seres libraries indicate: "Movies in series libraries support (names same as folder or contain " - Complete Movie")" which translates to these naming examples:
- same as folder name after scrub: Tenkuu no Shiro Laputa/Tenkuu no Shiro Laputa [a4e] [part1].mkv
- complete movie: Tenkuu no Shiro Laputa/Tenkuu no Shiro Laputa - Complete Movie - part 1 of 2 [a4e].mkv

Since you added "complete movie", they are considered ep1 so added together but not really as parts, but i see no way to make it happen differently (463-464 for parts adding function) but that should be acceptable

The issue is that some mini-series will use the same naming convention  "part x of y" and is to be split as different episodes, so as split movies in parts are rare nowadays, and you add a film to a series library, I cannot let it impact the series, as it is a series scanner after all, so you have to specify this is indeed a movie since it is in parts

Closing as working as designed

**Closed by ZeroQI** 2021-01-04 10:43 UTC
