### ISSUE TITLE
AniDB5 Possibility

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#230] opened 2019-09-17 19:51 UTC
I don't know if this is possible or not, but would doing some sort of AniDB5 mode where you pull from the AniDB relational mapping, but do your own custom relational mapping (locally) be possible?  I can think of a few cases, but the most obvious is the Monogatari series.  The [relational graph is so complex](https://anidb.net/anime/6327/relation/graph) that it's impossible to get the series in the right order.  It ends up being a mix of seasons and specials and none are entirely right.  

I was thinking there would be some top level folder like this (just an example):

```
Monogatari/anidb5.id
Monogatari/Bakemonogatari [anidb5-6327]
Monogatari/Nisemonogatari [anidb5-8658]
...
Monogatari/Koyomimonogatari [anidb5-11827]
```

In anidb5.id you could say which anidb ID goes to what season.  Kind of a custom season mapping?  

```
01|6327|Bakemonogatari
02|8658|Nisemonogatari
....
07|11827|Koyomimonogatari
```

Totally feel free to say no/deny this. Was just an idea that popped up today.

**Comment by ZeroQI** [comment] 2019-09-17 21:16
This series is emblematic as it is single handlely the worst to sort on disk...
I don't like your solution, a:
- s if a series is inserted in the middl
e, like a between season OAD, then you have to renumber some, but the scanner won't be ran for the folder again as it didn't change, therefore is not feasible. On top of that
- you require to know the anidbid
- need to change the series foldername.

I would use collections and store on disk as such the brackets are skipped but sorted per the numbers in them:
Monogatari/[01] Bakemonogatari
Monogatari/[02] Nisemonogatari
...
Monogatari/[12] Koyomimonogatari

Granted it won't be sorted in plex but you have the info browsing the folder
You could manually use as series title "bakemonogatari [01]" as sort title so it IS sorted in Plex... 
That is the reason for sort title and clever use of it i believe...

Forcing the sort title could be considered but we would need a working system... Do you have a reliable way to get watching order?

**Comment by sven-7** [comment] 2019-09-18 03:01
> if a series is released in the middle, like a between season OAD, then you have to renumber some, but the scanner won't be ran for the folder again as it didn't change, therefore is not feasible.

Very good point. Given the show's history, a possible resort in the future isn't unreasonable to expect. 

> Granted it won't be sorted in plex but you have the info browsing the folder

Exactly. I'm more concerned about the Plex organization instead of folder. 

I was just trying to think of clever ways to get it to be under one series title, but you're right. This might be one of those titles doomed to sticking with a collection and manually sorted order within Plex.

**Comment by ZeroQI** [comment] 2019-09-18 17:21
I sink you overlooked my last suggestion...
Leave as is the series title but change the sort_title to be ordered "bakemonogatari [01]" with in index the reading order, all in the same collection possibly...

**Comment by ZeroQI** [comment] 2019-09-21 15:54
@sven-7 Sven-7? What is your opinion in using the sort title field to countrol the grouping and display order?

**Comment by sven-7** [comment] 2019-09-21 16:07
Sorry, @ZeroQI for the delay. 

So that would mean importing all of the series (Bakemomogatari, Nisemomogatari, etc.) as standard AniDB, then custom changing the sort field so they appear next to each other and put them in a collection? Just trying to grasp your idea. It sounds like it’ll work.

**Comment by ZeroQI** [comment] 2019-09-21 16:16
@sven-7 Yes. Plex sort series alphabetically per the sort field, so using it to order the AniDB numbered series is more clever than fake seasons. You can put them or not in a collection but that is neater, especially if unsing the library setting to hide items in collection and single seasons, as you retain the possibility for specials for each series/movies

What could be done is custom movies/series collection and use the order to build a sort title (xxx collection #01) but the use case is too small in my opinion...

**Comment by sven-7** [comment] 2019-09-21 16:23
Okay - I’ll experiment with that today or tomorrow and let you know how it works out. Thanks!!

**Comment by EndOfLine369** [comment] 2019-09-22 01:46
Note, my understanding is that when you view a collection, it always sorts by year.

**Comment by deusxanime** [comment] 2019-09-22 02:13
Collections can be sorted by release date or alphabetical (sorting name/title in properties of the movie). You can change it by going to the edit properties for the collection and then go to the advanced section.

**Comment by EndOfLine369** [comment] 2019-09-22 03:08
Interesting. I see that now. But is also only a setting per collection. I doubt the agent could do anything about that as all it does is set the collection name against a series. So all collections would still be by year unless manually updated to title.

**Comment by ZeroQI** [comment] 2019-09-22 09:05
Playlist would have been cool...
Wondering if we can put:
- a collection text
- set it from the agent side
- put the recommended viewing order or collection text In it, where to get it from, or do a collection file like tvdb4 file for collections and select sort title for them...

**Comment by EndOfLine369** [comment] 2019-09-22 09:27
This seems like a lot of work for only a single series and it would also still not be automated. Only fully automated solutions should really be entertained.

Collections are already setup by the agent as is (EX: through AnimeList collections as all are under tvdbid="102261"). And collections cannot be modified by the agent other than the collection names a series is in (can it?). Only if you could edit the collection settings through the agent to change the sorting order can this realistically be taken forward for collections as a solution.

**Comment by EndOfLine369** [comment] 2019-09-22 09:34
@ZeroQI your main objection to the original anidb5 mapping setup is is mapping gets changed but series are not rescanned? The answer to that would be to only allow the mode when in a grouping folder. That would enforce the rescan to capture any mapping updates.
Create a new 'anidb5.mapping.xml' file in AAS and have it be the same configuration setup as tvdb4 of looking for a local mapping file then online.

**Comment by sven-7** [comment] 2019-09-22 17:41
The collection option worked, with a lot of manual effort. 

None of the Monogatari seasons import a collection, so you have to add them to the collection first. Second, you have to make sure your library is set up to display collections correctly.

**Comment by EndOfLine369** [comment] 2019-09-22 18:09
@sven-7, they will all be in a collection as noted above. Sounds like you don't have "AnimeLists" in your options list for collections. They would be in one collection as noted above as they are all against the same tvdbid.

**Comment by EndOfLine369** [comment] 2019-09-22 18:17
@sven-7, they will all be in a collection as noted above. Sounds like you don't have "AnimeLists" in your pref list for collections. They would be in one collection as noted above as they are all against the same tvdbid. Collections under "AnimeLists" are named under the series listed under S1E1 in tvdb.

Mine:
Prefs[collections            ] = Local, AniDB, TheMovieDb, TheTVDB, AnimeLists                  (Default: Local, AniDB, TheMovieDb, TheTVDB)

Also, the point of this ticket is also try to automate everything so no manual effort (other than setting the mapping). So if ZeroQI comments on the above about restricting to grouping folders, that would allow us to look at actually implementing your above recommendation like tvdb4 framework.

**Comment by EndOfLine369** [comment] 2019-09-22 18:20
And if grouping folder is enforced, that would also catch the 'Local' collection setup so you could have them in separate anidb5 but still together in collection.

**Comment by ZeroQI** [comment] 2019-09-22 18:45
If anything, i would like to avoid yet another forced id mode
I will add AnimeLists to the default collections. The issue is, the option will not change for people with the agent already present, but would if you use the checkbox to reset agent settings.

I don't think there is a way to gather the perfect order from the relationships as in this case there is a loop. Why can't people pull all in a collection and check a textfile or website with the recommended viewing order...  you can add '[01] ' in front of series title to order the folder so you know in which order to view, but sorting title seem more elegant.

**Comment by EndOfLine369** [comment] 2019-09-22 19:15
@ZeroQI True, people can indeed do that manual work. Always an option. 😄 

And creating a new force id for a single series is indeed a bit much. If we had a good handful where this would be helpful, I could see it validate the time of coding. When creating the (tvdb2/3/4|anidb2/3/4) modes you and I easily had multiple known examples to justify the work. And granted, those added complexity to the scanner/agent but added so much more flexibility for people to start using them without having to redo their while file setup.

@sven-7 are there more examples where this custom anidb#->season# would be needed/helpful aside from Monogatari?

**Comment by sven-7** [comment] 2019-09-23 14:59
@EndOfLine369 why do I get the sense you really want to be able to justify this fun project ;) 

Monogatari is the obvious example.  Especially if people want to differ from[ "airing order" to "chronological order"](https://www.animeimpulse.com/blog/2019/2/19/the-recommended-order-to-watch-the-monogatari-series)

Example: 

![XD9rxlu](https://user-images.githubusercontent.com/18091557/65436315-f642b580-ddef-11e9-9953-91936c27fcba.jpg)

Other examples:  [Suzumiya Haruhi](http://i.imgur.com/CMaAuPB.png)

There are a handful of legit examples in here:  https://www.reddit.com/r/anime/wiki/watch_order#wiki_the_melancholy_of_haruhi_suzumiya

Granted - this is a feature for advanced users who really want to be able to customize things. For me, I just wanted to have all of Monogatari split up as I think it should be, which isn't possible otherwise.  

By "tricking" Plex, I've hidden all collections from the library (manually hiding all but Monogatari), having the Monogatari collection "hide items in this collection" so that it shows up on its own.  From there, I've left it in broadcast order, but it's the best solution I've seen yet.  There seem to be a lot of missing metadata on AniDB and TVDB and possibly some scud lee errors, but it still "works". I had to manually add episode titles and descriptions for a few seasons. 

<img width="1340" alt="Screen Shot 2019-09-23 at 10 58 44 AM" src="https://user-images.githubusercontent.com/18091557/65437076-250d5b80-ddf1-11e9-84e6-b05aa9cb9a32.png">

**Comment by ZeroQI** [comment] 2019-09-23 16:07
So, do we scrap the anidb5 idea?
We need to fix Scudlee mapping if needs be regardless

**Comment by EndOfLine369** [comment] 2019-09-24 03:49
Sry @sven-7, two series doesn't seem worth the effort at this time. If we get a larger amount, or I get a lot of free time, we can maybe revisit this mode feasibility.

**Comment by EndOfLine369** [comment] 2019-09-29 02:08
@sven-7 closing for now. please kick up if you find some more examples and we can potentially reopen.

**Closed by EndOfLine369** 2019-09-29 02:08 UTC
Labels: enhancement

**Comment by sven-7** [comment] 2019-09-29 02:16
Agreed on closing. The one I found yesterday was the FATE series. Super messy relationship graph and many disagreements on order.

**Comment by sven-7** [comment] 2020-01-07 22:37
Realize that what I posted earlier is closely related to this.  Just posting the idea I had here for background. With the TVDB kind of shitting the bed, this would be an interesting feature. Maybe simpler than what I originally requested? 

----

Would there be any way we could support having a local relational map?  For example, that way I could determine which AniDB is mapped to which season.  I suppose I would need to define the relational map in each series, but that's not much of an issue.  I was thinking about it from a case of The Disastrous Life of Saiki K or even Monogatari.  Essentially, an AniDB entry can become a season within a single entry that the first entry starts.  Thoughts? 

I would have Saiki's look like this (without knowing how the format would need to be):

```
01|12112|Saiki Kusuo no Sainan (2016)
02|12691|Saiki Kusuo no Sainan (2018)
03|14189|Saiki Kusuo no Sainan: Kanketsuhen
04|14797|Saiki Kusuo no Sainan: Saishidou Hen 
```
