### ISSUE TITLE
Can't figure out the cause of this error

### ISSUE THREAD

**Issue by sheik124** [ZeroQI/Absolute-Series-Scanner#218] opened 2019-06-09 21:09 UTC
```
Jun 09, 2019 17:08:18.706 [37600] INFO - Plex Media Scanner v1.15.6.1079-78232c603 - Microsoft PC x64 - build: windows-x86 - GMT -04:00
Jun 09, 2019 17:08:18.706 [37600] INFO - Windows version: 6.2 (Build 9200), language en-US
Jun 09, 2019 17:08:18.707 [37600] INFO - 24 2600 MHz processor(s): Architecture=0, Level=6, Revision=15876 Processor Identifier=Intel64 Family 6 Model 62 Stepping 4, GenuineIntel
Jun 09, 2019 17:08:20.409 [1748] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "G:\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 952, in Scan
    anidb_str = read_cached_url(ANIDB_HTTP_API_URL+id, "anidb-%s.xml" % id)
  File "G:\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 205, in read_cached_url
    raise e
URLError: <urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>
Jun 09, 2019 17:08:20.410 [1748] ERROR - We got an error scanning in E:\Media\Anime
Jun 09, 2019 17:08:22.759 [1748] WARN - Scanning the location E:\Media\Anime did not complete
```

**Comment by ZeroQI** [comment] 2019-06-09 22:17
The scanner crashed (so will not scan again normally until Plex is restarted) as it could not read the AniDB series file which is used for openings and endings ep/titles.
I need the folder and filenames that crashes it, or you may have partial custom scanner logs in HAMA agent data folder logs...

**Comment by ZeroQI** [comment] 2019-06-09 22:32
Scanner.log
```
Library: 'no valid X-Plex-Token.id', root: 'E:\Media\Anime', path: 'Spice and Wolf [anidb-5406]', files: '15', dirs: '0'
Plex scan start: 2019-06-09 17:09:25,337000
=============================================================================================================================================================
Forced ID (series folder) - source: "anidb", id: "5406"
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc_count: {'and': 28, 'Lamb': 1, 'Group': 1, 'Silent': 1, 'Her': 1, 'Plot': 1, 'NCOP': 1, 'S1': 1, 'Youngsters': 1, 'Secret': 1, 'Biggest': 1, 'New': 1, 'Scheme': 1, '02': 1, '03': 1, '01': 1, '06': 1, '07': 1, '04': 1, '05': 1, '08': 1, '09': 1, "Shepherd's": 1, 'Farewell': 1, 'NCED': 1, 'Clothes': 1, 'Beginning': 1, 'Spice': 15, 'a': 3, 'Talent': 1, 'Virtuous': 1, 'Swirling': 1, 'Wolf': 28, 'the': 3, 'Quarrel': 1, '11': 1, '10': 1, '12': 1, 'Business': 1, 'Scales': 1, 'of': 2, 'Tail': 1, "Lovers'": 1, 'Past': 1, 'Distant': 1, 'Happiness': 1, 'Partner': 1, 'Helpless': 1, 'Best': 1}
misc_words: ['Spice', 'Wolf', 'and']
-------------------------------------------------------------------------------------------------------------------------------------------------------------
URL: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=5406', Creating cached file: 'c:\users\admini~1\appdata\local\temp\2\ASS-anidb-5406.xml'
Error reading url 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=5406', Exception: '<urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>'
Error downloading 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=5406', Exception: '<urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>'
```

Not showing in Plex is a scanner issue
- Try to see it the folder for 'c:\users\admini~1\appdata\local\temp\2\ASS-anidb-5406.xml' have appropriate write permissions, that is probably the cause, no right access by plex
- If Plex is running under the system account, then it accesses the file system as such. The proper way is to pick a regular user account (or create one especially for Plex) and select it in windows services used by Plex

**Comment by sheik124** [comment] 2019-06-09 22:39
Tried restarting Plex, no dice. Scanner log looks similar with a new timestamp.

Thank you for the quick reply! Have to run for a few hours but will attach all of the logs I can find in a reply.

By AniDB series file, do you mean "\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\AniDB\anime-titles.xml" or the XML file for the specific series ( \Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\AniDB )

My "PATH" for Plex is different, I've got it running from a separate high-endurance SSD to itself. Will try moving Plex to its own user account and report back. Right now "Plex Media Server.exe" is running under my regular user account (with Admin privileges) and the Plex Update Service is running as SYSTEM. The user account that Plex is running under has Full Control for "C:\Users\Administrator\AppData\Local\Temp\2" - there's no ASS-anidb XML files in there though.

**Comment by sheik124** [comment] 2019-06-09 22:40
You want all of these for all affected series and libraries?

[...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.hama.log (Agent logs)
[...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.system.log (show why the agent cannot launch)
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/root_folder.filelist.log (episodes info)
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/root_folder.scanner.log (episodes info)
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/root_folder.agent-search.log (guid assignment)
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/root_folder.agent-update.log (metadata update)

I will have to ZIP them once I'm back at the server but I will put it all together! Ty!

**Comment by ZeroQI** [comment] 2019-06-09 23:07
No need for logs anymore since you pasted some on HAMA bug report
The scanner downloaded the series xml and saved here  'c:\users\admini~1\appdata\local\temp\2\ASS-anidb-5406.xml'. You need to check write rights for subfolders of c:\users\admini~1\appdata\local\temp

**Comment by sheik124** [comment] 2019-06-10 18:47
It's bizarre, I added two new folders for Spice and Wolf, anidb-6169 and 6465...both showed up immediately and correctly populated with AniDB data after making the title changes from my HAMA issue. ie. No missing ep titles or TVDB order screwups.

I'm going to try the "Plex shuffle" (remove folder, scan, delete trash, replace, scan) and see if it shows up.

**Comment by sheik124** [comment] 2019-06-10 18:54
And the shuffle did it. Truly bizarre! Removed the folder, scan, empty trash, put the folder back but named "Spice and Wolf" (removed anidb-5406 from the folder name), scan. It showed up as "Spice and Wolf", then auto-matched and briefly displayed Spice and Wolf [anidb-5406] before becoming Ookami to Koushinryou.

I can't tell if it's correctly pulling AniDB episode titles (vs. TVDB order) because this series is mapped the same way on both, ie. "S1" on AniDB is "Specials, Episode 1" on TVDB. It did automatically detect the OP and ED as 101 and 151.

Thank you for all of your help.

Do you think the "Plex shuffle" would help for the show that isn't pulling down Episode Titles any more?

**Comment by sheik124** [comment] 2019-06-10 19:07
I think it is still focusing on TVDB data first,

![image](https://user-images.githubusercontent.com/2312934/59219460-8ab24080-8b90-11e9-903f-72dff02122b4.png)

That release date matches the first series, correct date on AniDB is 2009-07-09, the summary field is empty as well, same for II OVA

![image](https://user-images.githubusercontent.com/2312934/59219573-d4029000-8b90-11e9-8c03-ccd21ec2997c.png)

Full HAMA Settings from "\Plex Media Server\Plug-in Support\Preferences\com.plexapp.agents.hama.xml"

```
<?xml version='1.0' encoding='utf-8'?>
<PluginPreferences>
  <rating>AniDB, TheTVDB, MyAnimeList, TheMovieDb, OMDb | TheTVDB, AniDB</rating>
  <content_rating>AniDB,TheTVDB</content_rating>
  <art>TheTVDB, TheMovieDb, FanartTV</art>
  <EpisodeLanguagePriority>x-jat, en, ja</EpisodeLanguagePriority>
  <SerieLanguagePriority>x-jat, en, ja</SerieLanguagePriority>
  <themes>TVTunes, Plex</themes>
  <quotes>None</quotes>
  <thumbs>TheTVDB</thumbs>
  <year>AniDB</year>
  <duration>TheTVDB, AniDB, MyAnimeList, TheMovieDb, OMDb</duration>
  <rating_count>None</rating_count>
  <genres>TheTVDB, AniDB, MyAnimeList, TheMovieDb, OMDb</genres>
  <title>AniDB, TheTVDB | AniDB, TheTVDB</title>
  <MinimumWeight/>
  <content_rating_age>None</content_rating_age>
  <writers>AniDB,TheTVDB</writers>
  <collections>Local, AniDB, TheMovieDb, TheTVDB</collections>
  <absolute_index>AniDB, TheTVDB</absolute_index>
  <trivia>None</trivia>
  <tags>MyAnimeList</tags>
  <audience_rating_image>None</audience_rating_image>
  <rating_image>None</rating_image>
  <producers>AniDB,TheTVDB</producers>
  <audience_rating>None</audience_rating>
  <studio>AnimeLists, AniDB, TheTVDB, TheMovieDb</studio>
  <adult>true</adult>
  <posters>tvdb4, TheTVDB, TheMovieDb, FanartTV, AniDB</posters>
  <originally_available_at>AniDB,TheTVDB</originally_available_at>
  <roles>AniDB, TheTVDB</roles>
  <countries>TheMovieDb</countries>
  <title_sort>AniDB,TheTVDB</title_sort>
  <original_title>AniDB,TheTVDB</original_title>
  <OMDbApiKey>None</OMDbApiKey>
  <summary>TheTVDB, AniDB</summary>
  <reviews>None</reviews>
  <guest_stars>None</guest_stars>
  <directors>AniDB,TheTVDB</directors>
  <extras>None</extras>
  <tagline>TheMovieDb</tagline>
  <banners>TheTVDB</banners>
  <similar>None</similar>
  <PosterLanguagePriority>en</PosterLanguagePriority>
</PluginPreferences>
```

**Comment by ZeroQI** [comment] 2019-06-10 21:23
The issue is the scanner do not rescan a folder if the content didn't change even if the scanner crashed the first time or the scanner code change and would give different season and episode numbers...
If the ep is showing in plex then the scanner did its job and the plex dance could correct Plex database corruption

I just need the agent logs part that states which titles were available
hama log might miss bits since we do logs redirection

If you go to agent data folders: Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs then either in that folder or on with the library  name, a title.agent-update.log file...

That log will say why the title is what it is in one go...

**Comment by sheik124** [comment] 2019-06-10 22:40
[[anidb-11350][Coalgirls]_Owarimonogatari_(1920x1080_Blu-ray_FLAC).agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3274000/anidb-11350.Coalgirls._Owarimonogatari_.1920x1080_Blu-ray_FLAC.agent-update.log)

Owarimonogatari has no episode titles, dates, or summaries showing. I tried to do the Plex shuffle with a new folder name "Owarimonogatari" but no new log files show up.

[[anidb-14173] JJBA Golden Wind.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3274014/anidb-14173.JJBA.Golden.Wind.agent-update.log)

Golden Wind is missing episode info past Ep 14 I think.

[[anidb-8658] Nisemonogatari.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3274022/anidb-8658.Nisemonogatari.agent-update.log)

The entire Monogatari series is bugged out. Episode titles showed up for Bakemonogatari, Kizumonogatari pulled the summary from AniDB as well as the titles, but no dates or ep summaries.

[[anidb-8357][Edo] Kizumonogatari Trilogy v2 (1080).agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3274027/anidb-8357.Edo.Kizumonogatari.Trilogy.v2.1080.agent-update.log)

Let me know if you need more of them. They're all from _Logs/Anime, the main _Logs folder only has filelist.log and scanner.log.

**Comment by sheik124** [comment] 2019-06-10 22:45
[Owarimonogatari.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3274037/Owarimonogatari.agent-update.log)

Owarimonogatari after the shuffle.

**Comment by ZeroQI** [comment] 2019-06-11 00:14
It seems like the file was prevented to be created or was deleted afterwards (it's a temp file after all), all was working after a plex dance, so the scanner issue seem resolved and not caused by the scanner code or it would have happened again...

For the agent issues, logs show no meta for the episodes, no episodes detected at tvdb level
I need the scanner log to know the season, episode and filenames of files to reproduce the issue accurately

**Comment by sheik124** [comment] 2019-06-11 01:40
[Owarimonogatari [anidb-11350].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3274407/Owarimonogatari.anidb-11350.filelist.log)
[Owarimonogatari [anidb-11350].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3274408/Owarimonogatari.anidb-11350.scanner.log)

Looks like the same error in the scanner log as before.

```
URL: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11350', Creating cached file: 'c:\users\admini~1\appdata\local\temp\2\ASS-anidb-11350.xml'
Error reading url 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11350', Exception: '<urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>'
Error downloading 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11350', Exception: '<urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>'
```

**Comment by ZeroQI** [comment] 2019-06-16 07:58
Tried to access this URL and it works for me.
Can you check your antivirus (if called security suite) or firewall or try from another machine even mobile phone from the same internet connection?

**Comment by ZeroQI** [comment] 2019-06-26 05:38
Closing as no reply and specific to Plex or OS on given system, not scanner code

**Closed by ZeroQI** 2019-06-26 05:38 UTC
