### ISSUE TITLE
Please maintain stable releases

### ISSUE THREAD

**Issue by Ricadan** [ZeroQI/Absolute-Series-Scanner#179] opened 2018-08-30 02:53 UTC
I've been trying to move my Plex server to a new machine, but the recent series of commits has caused the scanner to fail to detect series it was once detecting correctly before, and because there is no release system I have no clue which commit of the scanner I need to use to get the correct behavior again. I appreciate the work that's being put into this, and I think having stable releases would greatly improve usability. Thanks!

**Comment by EndOfLine369** [comment] 2018-08-30 04:36
Please always use the most recent version if you are experiencing issues as any bugs could have already been resolved through other raised tickets or commits.
If you are seeing errors, please provide the required logs for us to look into the issue as noted in the README [Here](https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md#logs)

**Comment by dgw** [comment] 2018-08-30 04:59
@EndOfLine369 What @Ricadan is saying is, using the most recent version often _introduces_ more issues than it fixes due to regressions or unintended side effects of changes made to the master branch. Having users always use the latest commit means that they will encounter more issues in the long run.

Better to tag versions of the scanner with minimal (known) issues as "stable" and have users download those by default unless they want to help test the latest changes.

**Comment by Ricadan** [comment] 2018-08-30 05:01
Exactly, my point is that the very nature of only using the most recent version means that if I discover any bugs, my only option is to make a bug report and wait for it to be fixed. It'd be nice to also have the option of rolling back to a previous version that was known to be working.

**Comment by ZeroQI** [comment] 2018-08-30 12:50
Please contribute by using latest version and reporting issues.
- you can always list previous versions of ASS with GitHub and use that, that is another option
- The Legacy scanner I have included for that very reason. 
- You could use BABS scanner, it will never change.
- Why did you not kept the same file as the first server? After having the issue that seem more productive that complaining without giving any exemple of impacted series...

If I were to have a stable version systems, there would be no progress and changes...
I would have stopped developing as I am just trying to resolve bug reports at that point and I have a day job and little free time.

**Comment by Ricadan** [comment] 2018-08-30 18:54
1. The readme doesn't suggest doing anything like this, nor does it indicate that the scanner is being updated almost dozens of times a day. It took me a lot of time to figure out that the issue was that I was using a totally different scanner rather than how I was moving my library, and I expect many other users to experience the same because of the lack of documentation of this fact.

1. Again, the readme doesn't indicate anything about the existence of a legacy scanner/BABS scanner or what they're meant for, and I had no idea about them until you just told me.

1. I did keep the old scanner I was using and am using it now. The reason I rose this issue was not to complain about bugs for the scanner itself but to improve user experience by avoiding the same confusions I was going through while migrating my server.

Like you, I am also quite busy. I'd rather spend what little free time I have enjoying my anime rather than documenting how to reproduce bugs or having to argue why a stable versioning system is a good idea. If I have something that works, I'm just going to use it; I have little interest in being in the testing group for what largely seems to be quality of life updates and code reorganization, which generally provides little to no benefit to me.

**Comment by ZeroQI** [comment] 2018-08-30 20:13
I fix on bug reports as I do not use the software for myself and despite being self taught I brought this made from scratch Plex scanner the furthest I could and open sourced it so it benefits all and solves most issues within few days. I obviously want the code to be bug free but couple days by github standards is pretty good...

I will close this bug report as you resolved your issue but do not want to indicate which naming patterns were impacted.

**Closed by ZeroQI** 2018-08-30 20:13 UTC
